#!/usr/bin/env bash

set -e

ORIG_DIR="$PWD"
PATH_DIR_DOTFILES="$HOME/dotfiles"
echo "Updating dotfiles..."
echo "ORIG_DIR: $ORIG_DIR"
echo "PATH_DIR_DOTFILES: $PATH_DIR_DOTFILES"
if [ ! -d "$PATH_DIR_DOTFILES" ]; then
    echo "Cloning dotfiles..."
    git clone https://MiguelRodo/dotfiles.git "$PATH_DIR_DOTFILES"
    echo "Dotfiles cloned"
    echo "Changing directory to $PATH_DIR_DOTFILES"
    cd "$PATH_DIR_DOTFILES"
else
    echo "Changing directory to $PATH_DIR_DOTFILES"
    cd "$PATH_DIR_DOTFILES"
    echo "Pulling dotfiles..."
    git pull origin main
    echo "Dotfiles pulled"
fi

echo "Installing dotfiles..."
echo "Changing directory to $HOME"
cd $HOME
echo "Running install-hpc.sh"
dotfiles/install-hpc.sh
echo "Dotfiles installed"
echo "Changing directory back to $ORIG_DIR"
cd "$ORIG_DIR"
echo "Dotfiles updated"